adminUser:
  password: vault:jenkinsx/adminUser:password
  username: admin
enableDocker: false
pipelineUser:
  email: jordi.cami@madeofgenes.com
  token: vault:jenkinsx/pipelineUser:token
  username: jx-genomcore
prow:
  hmacToken: vault:jenkinsx/prow:hmacToken
